name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SECRET_KEY: SunMondayTUESDAYWednesdayTHURSDAYFridaySAT

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.4.1'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile --strict-peer-dependencies
        
    - name: Build
      run: pnpm build